import Head from 'next/head';
import { useContext, useState,useEffect } from 'react';
import { AppContext } from '@/settings/context/appContext';
import {GiMagnifyingGlass} from 'react-icons/gi';

export default function Home() {
  const [screenHeight, setScreenHeight] = useState(0);
  const { uid,setUid,email,setEmail } = useContext(AppContext);

  useEffect(() => {
    setScreenHeight(window.innerHeight - 60)
  },[])
  return (
    <>
      <Head>
        <title>Get Your Dream Job | Real Fast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/realfast_logo.PNG"/>
      </Head>
      <main  className={styles.container} style={{height:`${screenHeight}px`}}>
        <div className={styles.wrapper}>
          <div className={styles.searchBlock}>
            <div className={styles.searchPanel}>
            <input type='text' placeholder='eg. human resource manager' className={styles.search}/>
            <button className={styles.searchBtn}>search
              <GiMagnifyingGlass/>
            </button>
            </div>
            <p className={styles.message}>Your dream job is just a click away</p>
          </div>
          <div className={styles.otherActions}>
            <button className={styles.quickFinder}>Recent jobs</button>
            <button className={styles.quickFinder}>High paying jobs</button>
            <button className={styles.quickFinder}>Closing soon</button>
          </div>
          </div>
      </main>
    </>
  )
}

const styles = {
  container:'flex flex-col justify-center items-center px-16',
  wrapper:'w-full md:w-[720px] flex flex-col gap-16',
  searchBlock:'w-full',
  searchPanel:'flex flex-row gap-1',
  search:'w-full border border-indigo-200 rounded-full py-5 px-3',
  searchBtn:'flex justify-center items-center bg-indigo-800 text-white px-3 py-5 rounded-full cursor-pointer',
  message:'text-center mt-2',
  otherActions:'flex flex-col justify-center md:flex-row gap-4 md:justify-center',
  quickFinder:'w-full w-[200px] h-[60px] md:w-[200px] md:h-[120px] bg-indigo-800 border-4 border-indigo-800 shadow-md rounded-xl text-lg text-indigo-200'
}

